server {
    listen 80;

    root /usr/share/nginx/html;
    index webrtc_play.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # 代理 SRS API，避免跨域
    location /srs/ {
        proxy_pass http://srs:1985/;
        proxy_set_header Host $host;
    }
}
